-- --------------------------------------------------------
-- Hôte :                        localhost
-- Version du serveur:           5.7.24 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Listage de la structure de la base pour cerisy
CREATE DATABASE IF NOT EXISTS `cerisy` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `cerisy`;

-- Listage de la structure de la table cerisy. intervenants
CREATE TABLE IF NOT EXISTS `intervenants` (
  `id` char(50) NOT NULL,
  `url_photo` varchar(255) DEFAULT NULL,
  `biographie` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Listage des données de la table cerisy.intervenants : ~58 rows (environ)
/*!40000 ALTER TABLE `intervenants` DISABLE KEYS */;
INSERT INTO `intervenants` (`id`, `url_photo`, `biographie`) VALUES
	('610jeanlouislaville', NULL, 'Jean-Louis Laville, est membre du LISE (laboratoire interdisciplinaire pour la sociologie économique), professeur du Cnam, où il est titulaire de la Chaire  « Économie Solidaire » et enseigne dans le cadre du mastère Sciences du travail et de la société « Ressources humaines et sociologie », et chercheur à l’IFRIS, où il coordonne l’axe « Innovation sociale » du LabEx SITES (Laboratoire d’excellence Sciences, innovation et techniques en société) consacré à l’innovation. Également coordinateur européen du Karl Polanyi Institute of Political Economy, il est membre fondateur et secrétaire général du réseau européen EMES qui organise des activités scientifiques internationales régulières sur l’innovation sociale, et du réseau sud-américain RILESS (Réseau de chercheurs latino-américains sur l’économie sociale et solidaire).'),
	('611philippeeynaud', NULL, 'Philippe Eynaud est professeur en sciences de gestion à l’IAE de Paris, Université Paris 1 Panthéon Sorbonne, et membre du groupe de recherche en gestion des organisations (Gregor) de l’IAE de Paris.'),
	('612stephaneveyer', NULL, 'Ancien dirigeant emblématique de la coopérative Coopaname, Stéphane Veyer est l\'une des chevilles ouvrières du mouvement des coopératives d\'activités et d\'emploi, et un acteur de l\'économie sociale. \r\n'),
	('613gheorgheciascai', NULL, 'Gheorghe Ciascai a deux maîtrises en philosophie et en sciences politiques à l\'université Babes-Bolyai de Cluj-Napoca (Roumanie), un diplôme conjoint en droit européen d\'affaires à l\'université Paris I Sorbonne et à l\'université de Bucarest. Il a obtenu le titre de docteur en philosophie à l\'université Babes-Bolyai de Cluj-Napoca. Depuis 2010, il est maître de conférences à la Faculté de Sciences Politiques de l\'université chrétienne Dimitrie Cantemir de Bucarest où il a dirigé le master Économie sociale entre 2011 et 2013. Ses domaines d\'intérêt sont : relations internationales, études européennes, communication et relations publiques internationales, économie sociale, philosophie des sciences sociales. Entre 2014 et 2016, il a participé aux projets de création d\'entreprises sociales en Roumanie financées par le Fonds social européen. Dans le domaine de l\'économie sociale, il a publié l\'article « La mise en valeur des friches industrielles : un projet roumain d\'entreprise sociale à Vad dans le cadre d\'un programme de l\'Union européenne », dans Cahier de recherche Chaire ESS - UPEM, numéro spécial (2016).\r\n'),
	('614giuseppelirosi', NULL, 'Giuseppe Li Rosi est président de l’association Simenza-Cumpagnìa Siciliana Sementi Contadine. Créée en février 2016 avec le projet de conserver et revaloriser la biodiversité agraire en Sicile, cette association accompagne les agriculteurs vers la gestion de la biodiversité et la création de filières courtes, avec un modèle d’agriculture et des systèmes de distribution soutenables.'),
	('615marclourdaux', NULL, 'Après dix ans passés à la tête de l’office de tourisme du Champsaur-Valgaudemar, Marc Lourdaux a créé et coordonne l\'association Échanges Paysans des Hautes-Alpes.'),
	('616pedrohespanha', NULL, 'Sociologue, professeur à la faculté d’économie de Coimbra, Pedro Hespanha est membre fondateur du Centre des études sociales.'),
	('617stephanieleyronas', NULL, 'Stéphanie Leyronas est chargée de recherche pour l\'Agence française de développement. Ses domaines d\'expertise concernent les communs, la gestion des ressources naturelles, la gestion des services et l\'économie du développement.'),
	('618lionelmaurel', NULL, 'Directeur adjoint scientifique à l’Institut national des sciences humaines et sociales du CNRS, Lionel Maurel est juriste et conservateur de bibliothèques, et auteur du blog S.I.Lex, au croisement des sciences de l’information et du droit.'),
	('619jeanfrancoisdraperi', NULL, 'Directeur de la revue Recma créée en 1921 par Charles Gide, Jean-François Draperi inscrit ses recherches dans la tradition de l’économie sociale.'),
	('61hervedefalvard', 'https://cloud.scic-tetris.org/s/Kg6OEbOZZSLXDp5', 'Docteur en économie et maître de conférences à l’université Gustave Eiffel (UGE), Hervé Defalvard est auteur de plusieurs ouvrages, dont La Révolution de l’économie en dix leçons (Éditions de l’Atelier, 2015 ; Prix du livre ESS). Il a co-organisé le colloque "Territoires solidaires en commun : controverses à l\'horizon du translocalisme".'),
	('620lauraaufrere', NULL, 'Doctorante au CEPN de Paris 13, Laura Aufrère était coordinatrice à l’UFISC, fédération représentante des structures artistiques et culturelles se reconnaissant de l’ESS. Son sujet de thèse porte sur les artist-run spaces, des espaces auto-gérés par des communautés d’artistes qui tentent de s’organiser en commun(s) et selon les principes de l’ESS.'),
	('621cecileoffroy', NULL, 'Cécile Offroy est chercheure attachée à l’IRIS/EHESS et responsable d’études à Opale, centre de ressources Culture et ESS. Ses travaux portent principalement sur les enjeux qui traversent les organisations du champ artistique et culturel (associations, lieux intermédiaires, lieux de diffusion…). Elle privilégie la recherche-action et s’attache à impliquer collectivement les acteurs dans les processus d’élaboration.\r\n'),
	('622raphaellhomme', NULL, 'Raphaël Lhomme est actuellement professeur de Sciences économiques et sociales (SES) au lycée Raoul-Follereau de Belfort, en Franche-Comté. Il est par ailleurs référent pour l\'Économie sociale et solidaire (ESS) et les droits culturels au sein de la revue culturelle en ligne Profession Spectacle. Il a d\'ailleurs rédigé pour cette dernière une série d\'articles sur les relations entre ESS, droits culturels et approche par les capabilités.'),
	('623sylvainbaudet', NULL, 'Sylvain Baudet travaille pour Territoires Conseils, service d’expertise de la Banque des territoires qui accompagne les collectivités territoriales.'),
	('624fabienjouron', NULL, 'Fabien Jouron est responsable régional du groupe La Poste en Pays de la Loire.'),
	('625ericlesueur', NULL, 'Éric Lesueur est le président exécutif de 2EI, filiale du groupe Veolia dédiée à l\'innovation et au conseil sur les services urbains pour les villes et territoires durables, notamment dans le domaine de l\'innovation sociale. Éric Lesueur est en particulier le managing director de Grameen Veolia Water, social business pour l\'eau potable au Bangladesh, en partenariat avec Mohamed Yunus. 2EI a également développé POP Up, un réseau international d\'incubateurs d\'entreprenariat social autour des activités de Veolia. Diplômé de l\'École polytechnique, Éric Lesueur a rejoint Veolia en 1993 où il a occupé plusieurs responsabilités, comme directeur Environnement ou directeur adjoint de la R & D, avant de créer 2EI en 2008.'),
	('626nicolaschochoy', NULL, 'Nicolas Chochoy est docteur en sciences économiques, chercheur titulaire au Centre de recherche sur les institutions, l’industrie et les systèmes économiques d’Amiens (CRIISEA) et maître de conférences en sciences économiques. Animé par la métaphore de l’encastrement politique de l’économie, il s’est spécialisé dans l’analyse des phénomènes collectifs. Il dirige l’Institut Godin depuis sa création en 2007.'),
	('627silkehelfrich', NULL, 'Chercheuse et militante allemande sur les communs. Silke Helfrich est membre de l’Institute for Advanced Sustainability Studies (IASS) de Potsdam et membre fondatrice, avec Michel Bauwens et David Bollier, du Commons Strategies Group. Elle a notamment publié avec David Bollier en 2015 Patterns of commoning (Levellers Press, 2015), ouvrage qui rassemble une cinquantaine d’articles qui décrivent des communs susceptibles d’ouvrir la voie à de nouvelles formes de production, de gouvernance et de modes de vie.'),
	('628francoisxavierviallon', NULL, 'François-Xavier Viallon est chercheur en science politique à l’Université de Lausanne. Ses domaines de recherche sont la mise enœuvre des politiques publiques, la gestion des ressources naturelles et la gouvernance de la propriété, notamment sous l’angle des communs.'),
	('629corinnebebin', NULL, 'Corinne Bebin est diplômée de l\'IEP Paris et de l\'INSHEA. Maire-adjoint déléguée aux affaires sociales et à la Santé de la Ville de Versailles. Vice-présidente du CCAS. Présidente de la Société Coopérative d\'Intérêt Collectif (SCIC) Solidarité Versailles Grand Age. Élue locale depuis 10 ans, l\'expérience de l\'accompagnement de la vulnérabilité enrichit quotidiennement ses réflexions éthiques sur l\'action politique. Présidente de la Commission spécialisée Médico-Sociale - CRSA - ARS Ile de France.'),
	('62elisabettabuccolo', 'https://cloud.scic-tetris.org/s/EodeaOoYM1hFsSN', 'Elisabetta Bucolo est sociologue, maîtresse de conférences au Cnam. Elle est responsable du Master « Intervention et développement social : Économie sociale et solidaire ». Elle a co-organisé le colloque "Territoires solidaires en commun : controverses à l\'horizon du translocalisme".'),
	('630ericbonneau', NULL, 'Éric Bonneau gère la SCIC Ecoreso, installée depuis novembre 2017 à Gourfaleur, près de Saint-Lô. Cette plateforme collecte, répare et revend toutes les « aides techniques » pour l’autonomie, qui permettent le maintien à domicile. Cela va du lit médicalisé au fauteuil roulant, en passant par les déambulateurs, les sièges adaptés pour les douches, les barres d’appui, etc. Le matériel récupéré va être réparé puis revendu à petit prix ou loué, notamment à tous ceux qui n’ont pas beaucoup de moyens ou qui ont des restes à charge très importants, malgré les aides de la Sécurité sociale ou du Département.'),
	('631olivierbenoit', NULL, 'Olivier Benoit est un militant de l\'association Aides créée en 1984. Aides est la première association de lutte contre le VIH/sida et les hépatites virales en France. Aides s’inscrit dans une démarche communautaire en santé qui considère la personne comme actrice de sa santé et en maîtrise d’un vrai savoir profane, aux côtés du savoir savant.'),
	('632camillefontenelle', NULL, 'Camille Fontenelle est membre d\'Enerterre qui a été conçu comme une réponse locale à l\'inconfort rencontré dans les logements situés en zone rurale diffuse. Initié par le Parc naturel régional des Marais du Cotentin et du Bessin, il contribue à inscrire ce territoire dans une politique plus large de transition énergétique. Par ailleurs, l\'utilisation de matériaux naturels locaux et géo-sourcés, peu émetteurs de CO2 comme la terre crue, emblème du mode constructif sur le territoire, ou les fibres végétales (paille, lin, chanvre) est mise en avant dans les travaux réalisés.'),
	('633josephhaeringer', NULL, 'Sociologue, Joseph Haeringer a été associé au LISE-CNRS (laboratoire interdisciplinaire pour la sociologie économique) après avoir exercé les fonctions de direction d\'association. Enseignant à Sciences Po Formation, il était coresponsable pédagogique de l\'Executive Master «Sociologie de l\'association et action dirigeante». Ses travaux de recherche portent notamment sur les associations d\'action sociale et médico-sociale. Dans cette perspective, il a publié divers articles ou participé à divers ouvrages sur l\'évaluation, la gouvernance et la participation des usagers. La Démocratie : un enjeu pour les associations d\'action sociale et médico-sociale (Desclée De Brouwer, 2008) est le dernier ouvrage qu\'il a dirigé. Il prépare un ouvrage collectif sur le changement dans les associations.\r\n'),
	('634jacquesjouet', NULL, 'Jacques Jouet est dramaturge, essayiste, nouvelliste, poète et romancier français. Il appartient à l\'Oulipo (Ouvroir de littérature potentielle fondé par François Le Lionnais et Raymond Queneau) depuis 1983. Avec d’autres oulipiens (François Caradec, Paul Fournel, Hervé Le Tellier), il animait l’émission « des Papous dans la tête » (France Culture).'),
	('635arnaudassie', NULL, 'Arnaud Assié est doctorant contractuel au CIRED (Centre international de recherche sur l\'environnement et le développement) et son travail de doctorat porte sur les « Fonds citoyens et plateformes numériques de financement participatif pour les énergies renouvelables : nouveaux intermédiaires, nouvelles valeurs et nouveaux partages en vue de la transition énergétique ».\r\n'),
	('636michelcarre', NULL, 'Michel Carré est militant bénévole de l\'implication citoyenne pour une réelle démocratie solidaire et écologique. Retraité (64 ans) de la formation professionnelle d\'agriculteurs, de responsables associatifs et de collectivités en milieu rural. Il préside l\'association « Énergies Citoyennes en Pays de Vilaine » (EPV) depuis trois ans.\r\n'),
	('637pierreguelman', NULL, 'Juriste, titulaire d\'un DEA Finances publiques et d\'un DESS en urbanisme, Pierre Guelman est rentré à EDF en 2002, en tant que chef de mission stratégie de la branche « Collectivités », puis directeur de la mission «Concessions, partenariats et communication », avant de devenir en mai 2014, directeur des Affaires Publiques d’Enedis. Auparavant, il a exercé en cabinet ministériel les fonctions de conseiller parlementaire, à l’Educationnationale et à Matignon.'),
	('638faneliecarreyconte', NULL, 'Fanélie Carrey-Conte est secrétaire générale et directrice coopération chez Enercoop et ancienne députée (Paris 20e).'),
	('639melainecervera', NULL, 'Melaine Cervera, docteur en sciences économiques, maître de conférences en sociologie à l\'université de Lorraine et co-fondateur de l\'association de promotion des expérimentations sociales (APEX), étudie la co-construction de l\'action publique entre les pouvoirs publics et les associations en termes d\'accompagnement des publics fragiles. Les dynamiques d’économie solidaire et des communs sur les territoires constituent pour lui un terrain d\'étude privilégié pour repenser les analyses de la solidarité et de l\'autonomie. Il fait partie du groupe des capteurs de liens qui a œuvré aux côtés des co-organisateurs et de l\'équipe des Éditions de l\'Atelier pendant et après le colloque pour vous proposer ce livre et ce site compagnon.'),
	('63genevievefontaine', 'https://cloud.scic-tetris.org/s/M4RS81wwOk2EiMq', 'Geneviève Fontaine est docteur en économie salariée de l\'Institut Godin et l’une des initiatrices du Pôle territorial de coopération économique (PTCE) TETRIS (Transition écologique territoriale par la recherche et l’innovation sociale) basé à Grasse. Elle a co-organisé le colloque "Territoires solidaires en commun : controverses à l\'horizon du translocalisme".'),
	('640isabelledelannoy', NULL, 'Activiste, Isabelle Delannoy est l’auteure de L’Économie symbiotique. Régénérer la planète, l’économie et la société, Arles, Actes Sud, 2017.'),
	('641denisdupre', NULL, 'Après avoir passé quinze ans dans divers organismes bancaires, Denis Dupré enseigne l\'éthique, la finance et l\'écologie territoriale depuis 20 ans à l\'université Grenoble-Alpes et à l\'Ensimag (Institut national polytechnique de Grenoble). Il a écrit une dizaine de livres sur l\'éthique, la finance et la monnaie disponible [souvent en version gratuite]. Denis Dupré alerte, depuis 1998, sur les risques de démesure de notre système financier et sur la puissance exponentielle de l\'économie nuisible. Il a proposé des actions collectives pour remettre la finance à sa place en vue d\'élaborer une économie au service des projets d\'autonomie des hommes et a participé à quelques initiatives pour réformer la finance (Finance et biens communs à Genève, Finance And Sustainability en France, Stopevasionfiscale).\r\n'),
	('642mariefare', NULL, 'Marie Fare est économiste, maître de conférences à l\'université Lumière-Lyon 2 et membre du laboratoire Triangle (UMR 5206). Ses travaux se concentrent sur la pluralité monétaire et particulièrement sur les monnaies locales, sociales et complémentaires, analysées au regard des enjeux du développement territorial soutenable.'),
	('643nicolealix', NULL, 'Nicole Alix est présidente de La Coop des Communs, pour construire des alliances entre économie sociale et solidaire et les communs. HEC 74, elle a travaillé quinze ans au Crédit coopératif dont elle a été la directrice du développement et vingt-cinq ans dans le monde associatif de l\'action sociale et la santé (DGA de l\'UNIOPSS, créatrice du « Comité de la Charte pour le don en confiance », DG du groupe de Maisons de retraite Isatis).\r\n'),
	('644denisdurand', NULL, 'Denis Durand, diplômé de l\'Institut d\'études politiques de Paris et de l\'université Paris I, a été directeur adjoint à la Banque de France où il a également exercé des responsabilités syndicales. Il a été membre du Conseil économique et social puis du Conseil économique, social et environnemental. Il est actuellement codirecteur de la revue Économie et politique.\r\n'),
	('645sylviebarros', NULL, 'Précédemment chargée de l’ESS pour la mairie de Thiers pour redynamiser l’abandonnée Vallée des usines, Sylvie Barros est aujourd\'hui directrice de l\'entreprise à but d\'emploi de Thiers. Elle fait partie du groupe des capteurs de liens qui a œuvré aux côtés des co-organisateurs et de l\'équipe des Éditions de l\'Atelier pendant et après le colloque pour vous proposer ce livre et ce site compagnon.\r\n'),
	('646benedettacelati', NULL, 'Benedetta Celati, docteure en droit public de l\'économie à l\'université de Pise et en sciences économiques à l\'université Paris-Est, est actuellement post-doctorante sur la thématique des politiques publiques et des instruments juridiques pour la valorisation socio-économique des territoires, également dans la perspective de la régénération urbaine. Pour sa recherche doctorale, elle a abordé le sujet des dynamiques socio-économiques locales et de leur interaction avec le droit, en étudiant, sous le prisme de l\'économie sociale et solidaire comme vecteur de transformation sociale, des communautés énergétiques durables et des monnaies alternatives.\r\n'),
	('647maitejuan', NULL, 'Maïté Juan est docteure en sociologie, post-doctorante au GIS Démocratie et participation, MSH Paris Nord (CNRS) et chercheure associée au programme de recherche « Démocratie et économie plurielles » du Collège d\'études mondiales (FMSH). Ses travaux se situent à la croisée de la démocratie participative et de l\'économie solidaire, et tendent à articuler science politique et sociologie économique. Elle mène actuellement une étude postdoctorale sur les « recherches participatives ».\r\n'),
	('648anadubeux', NULL, 'Ana Dubeux, docteur en sociologie, diplômée de l\'université de Paris I, est actuellement professeur du département de Sciences de l\'éducation à l\'université fédérale rurale de Pernambouc au Brésil, membre du Centre de recherche en agroécologie et paysannerie et de l\'Incubateur technologique de coopératives populaires de cette université. Travaillant toujours dans la perspective de la recherche-action avec des mouvements sociaux liés à l\'agroécologie et à l\'économie solidaire, ses recherches lient ces thématiques à la quête d\'un nouveau sens au processus de construction de connaissances et de la science à partir de la perspective des épistémologies du sud et des communs.\r\n'),
	('649colinrobineau', NULL, 'Les travaux de Colin Robineau se situent au croisement de la sociologie, des sciences de l\'information et de la communication et de la science politique. Accordant une place centrale à la démarche ethnographique, ses recherches interrogent de façon transversale des objets variés : les formes contemporaines de l\'engagement, les modalités d\'organisation et de politisation d\'espaces publics locaux et contestataires, les processus de socialisation politique ainsi que les conditions de possibilité de la critique ordinaire de l\'ordre social.\r\n'),
	('64philippechemla', 'https://cloud.scic-tetris.org/s/1ZQsUde4ZvV5QkR', 'Philippe Chemla est l\'un des initiateurs du Pôle territorial de coopération économique (PTCE) TETRIS (Transition écologique territoriale par la recherche et l’innovation sociale) basé à Grasse. Il y coordonne le développement du tiers-lieu de la transition écologique (Sainte-Marthe) labelisé Fabrique Numérique de Territoire en 2019. Il fait partie du groupe des capteurs de liens qui a oeuvré aux côtés des co-organisateurs et de l\'équipe des Editions de l\'Atelier pendant et après le colloque pour vous proposer ce livre et ce site compagnon.'),
	('650benjamincoriat', NULL, 'Économiste français spécialisé en économie industrielle, de l’innovation et de la propriété intellectuelle, Benjamin Coriat est membre des Économistes atterrés et membre fondateur de La Coop des Communs.\r\n'),
	('651vivianehamon', NULL, 'Viviane Hamon (École supérieure de commerce de Paris - DEA Sciences de gestion - master d\'anthropologie) est consultante indépendante depuis 1985. Son activité est centrée sur l\'application du marketing sociétal aux questions du développement durable des territoires (agriculture, tourisme, économie locale) et de la transition énergétique. Sur ces sujets, elle contribue à la création, à la mise en œuvre et à l\'évaluation de politiques publiques auprès des collectivités territoriales (EPCI et de Régions) et d\'agences nationales (Ademe, Anah, Plan Bâtiment durable…). En 2006, elle a participé à la création du label Bâtiments durables méditerranéens et est aujourd\'hui membre du Comité d\'orientation stratégique de l\'association Envirobat-BDM. Elle fait partie du groupe des capteurs de liens qui a œuvré aux côtés des co-organisateurs et de l\'équipe des Éditions de l\'Atelier pendant et après le colloque pour vous proposer ce livre et ce site compagnon.\r\n'),
	('652jeanlouisbancel', NULL, 'Président du Crédit Coopératif et co-fondateur de La Coop des Communs, Jean-Louis Bancel est également président de l\'Alliance coopérative internationale (ACI).\r\n'),
	('653noemiedegrenier', NULL, 'Diplômée de l\'IEP de Lille et de l\'Université de Louvain-la-Neuve, Noémie de Grenier est co-directrice de Coopaname, une coopérative d’activité et d’emploi francilienne.\r\n'),
	('654lescapteursdeliens', NULL, 'Une équipe de neuf capteurs et capteuses chargés de cueillir, au fil de leur poussée dans les différents lieux et temps du colloque, les liens de toutes sortes : liens entre les territoires, au présent ou au futur, entre les personnes, liens réels ou virtuels, tenant lieu d’exemples, révélant une difficulté, manifestant un désaccord. Un quartier général avait été établi dans un des lieux de Cerisy, à l’Étable, pour déposer ces liens  à l’aide de post-it. Les capteurs de liens sont décrits avec poésie et fantaisie à la page 176 du livre.\r\n'),
	('655edithheurgon', NULL, 'Docteur en mathématiques appliquées (Paris VI), Édith Heurgon a été pendant plusieurs années responsable de la mission Prospective de la RATP. Elle est la directrice emblématique du Centre culturel international de Cerisy-la-Salle depuis 2006. Voir le livre page 197 et suivantes.\r\n'),
	('656lechateaudecerisy', NULL, 'Le château de Cerisy est un intervenant à part entière des colloques qui s\'y déroulent. Le Centre culturel international de Cerisy propose, chaque année, de fin mai à début octobre, dans le cadre accueillant de ce château construit au début du XVIIe siècle, monument historique, des rencontres réunissant artistes, chercheurs, enseignants, étudiants, acteurs économiques et sociaux, mais aussi un vaste public intéressé par les échanges culturels et scientifiques. Tout au long du livre et dans les ressources de cette page vous pouvez découvrir et retrouver les spécificités et apports des différents espaces qui le composent. \r\n'),
	('657lequipedecerisy', NULL, 'Édith Heurgon assure l\'animation du Centre, avec le concours de ses neveux (Anne Peyrou-Bas, Christian Peyrou et Dominique Peyrou), groupés dans la Société civile du château de Cerisy, et le soutien d\'une équipe efficace et dévouée, dirigée par Philippe Kister.\r\n'),
	('658-participants-non-intervenants', NULL, 'Les colloques de Cerisy n\'existeraient pas sans leurs participants et la sagacité de leurs interventions, remarques et questions qui alimentent les débats en sortant parfois les intervenants de leur zone de confort !\r\n'),
	('65barbarabinbarrois', NULL, 'Barbara Blin-Barrois a animé la genèse de la Scic ôkhra qui porte le pôle territorial de coopération économique Matières et Couleurs du Luberon-Provence et qui a créé le Conservatoire des ocres et de la couleur, implanté en région Provence-Alpes-Côte d’Azur. Cette dynamique débute en 1994 lorsque les deux fondateurs, dont Barbara Blin-Barrois, décident d’ancrer leur méthodologie de redynamisation économique des savoirs techniques – méthodologie inspirée de celle des économusées du Québec [entreprises artisanales œuvrant dans le secteur des métiers d\'art ou de l\'agroalimentaire] – à Roussillon, au pays des ocres. '),
	('66fatimamostafaoui', NULL, 'Fatima Mostefaoui agit pour que les habitants des Flamants à Marseille soient écoutés et deviennent acteurs du devenir de leur quartier. Elle a notamment occupé récemment le devant de la scène, propulsée porte-parole d’un collectif de femmes des cités de Marseille réclamant qu’une partie des biens saisis au crime organisé (des fraudes fiscales des entreprises aux malversations des cols blancs, en passant par ce qui se passe dans les cités) soit réaffectée à des projets d’économie solidaire pour les quartiers en déshérence.'),
	('67rachidcherfaoui', NULL, 'Rachid Cherfaoui a créé en 2004 et dirigé la Scic Maison d’économie solidaire qui porte le Pôle territorial de coopération économique Idesol sur le pays de Bray. Initié par des structures de l’insertion par l’activité économique, ce PTCE regroupe aujourd’hui de très nombreuses parties prenantes publiques et privées rassemblés par l\'ambition d’être des « développeurs de territoire » par la coopération de long terme. Rachid Cherfaoui est également président de l\'Institut Godin, premier centre de transfert en pratiques solidaires et innovation sociale de France.\r\n'),
	('68claudesicart', NULL, 'Claude Sicart est président de l’association Le Pôle S à Villeneuve-la-Garenne, entreprise d’insertion et d’éducation populaire. Militant de l’économie sociale et solidaire, il est aussi entrepreneur et participe à de nombreuses initiatives en faveur des habitants des quartiers de la politique de la ville. Il est membre du Conseil national des villes.\r\n'),
	('69danielleguillou', NULL, 'Engagé dans le projet « Territoires zéro chômeur de longue durée » depuis 2015, Daniel Le Guillou est actuellement vice-président de l\'entreprise à but d\'emploi du territoire expérimental de Thiers (63) et chargé de la capitalisation au sein de l\'association « Territoires zéro chômeur de longue durée ».\r\n');
/*!40000 ALTER TABLE `intervenants` ENABLE KEYS */;

-- Listage de la structure de la table cerisy. timeline
CREATE TABLE IF NOT EXISTS `timeline` (
  `id` varchar(128) NOT NULL,
  `nom` varchar(255) DEFAULT NULL,
  `date` varchar(100) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `edition` varchar(255) DEFAULT '2019',
  `order` smallint(6) DEFAULT NULL,
  `showintimeline` smallint(6) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Listage des données de la table cerisy.timeline : ~34 rows (environ)
/*!40000 ALTER TABLE `timeline` DISABLE KEYS */;
INSERT INTO `timeline` (`id`, `nom`, `date`, `url`, `edition`, `order`, `showintimeline`) VALUES
	('dp1formesdesolidariteetcommun', 'DP 1 - Formes de solidarité et commun', 'Samedi 13 Juillet', 'https://cloud.scic-tetris.org/s/t4sry40KbBdNfTb', '2019', 6, 1),
	('dp2regardscroisesnordsuduneepistemologiecommune', 'DP 2 - Regards croisés Nord-Sud, une épistémologie commune?', 'Dimanche 14 Juillet', 'https://cloud.scic-tetris.org/s/qvgZ0n6xhwGFY9h', '2019', 8, 1),
	('dp3valeursetcommunspourlesterritoires', 'DP 3 - Valeurs et communs pour les territoires', 'Lundi 15 Juillet', 'https://cloud.scic-tetris.org/s/PGl4JkXEogPkgFq', '2019', 13, 1),
	('dp4pouvoirspublicsetcommun', 'DP 4 - Pouvoirs publics et commun', 'Lundi 15 Juillet', 'https://cloud.scic-tetris.org/s/ItXT8tG7d58nyP7', '2019', 15, 1),
	('dp5emancipationetcommun', 'DP 5- Emancipation et commun', 'Mercredi 17 Juillet', 'https://cloud.scic-tetris.org/s/hWpVwwrtaZ730Wm', '2019', 21, 1),
	('dp6monnaieetcommun', 'DP 6 - Monnaie et commun', 'Mercredi 17 Juillet', 'https://cloud.scic-tetris.org/s/Z2Ypw3fOazqc54v', '2019', 23, 1),
	('dp7criteresetoutilsdegestionetcommun', 'DP 7 - Critères et outils de gestion et commun', 'Mercredi 17 Juillet', 'https://cloud.scic-tetris.org/s/CV3psJTfKMmGU4S', '2019', 24, 1),
	('dp8droitcommunetterritoire', 'DP 8 - Droit, commun et territoire', 'Jeudi 18 Juillet', 'https://cloud.scic-tetris.org/s/rE2GNADxrEFa7IJ', '2019', 28, 1),
	('dp9cooperativesetcommunpourquellessolidarites', 'DP 9 - Coopératives et commun pour quelles solidarités?', 'Jeudi 18 Juillet', 'https://cloud.scic-tetris.org/s/POUk7wApQ8ULHnJ', '2019', 29, 1),
	('enjeuxetcontroverses1', 'Enjeux et controverses - 1', 'Lundi 15 Juillet', 'https://cloud.scic-tetris.org/s/X6JoajHaH9eicRi', '2019', 14, 1),
	('enjeuxetcontroverses2pouvoirspublicsetcommuns', 'Enjeux et controverses 2 - Pouvoirs publics et communs', 'Mercredi 17 Juillet', 'https://cloud.scic-tetris.org/s/gOwqcAV8ApWmLpk', '2019', 25, 1),
	('horslesmursvisitesdeterrains', 'Hors les murs - visites de terrains', 'Mardi 16 Juillet', 'https://cloud.scic-tetris.org/s/EWFcvdEPSQmQ3BM', '2019', 18, 1),
	('introduction', 'Introduction', 'Samedi 13 Juillet', 'https://cloud.scic-tetris.org/s/JRqfNEivO6IQrJo', '2019', 2, 1),
	('lelivre', 'le livre', 'Après le colloque', 'https://cloud.scic-tetris.org/s/yYbYJ6yUQ8twWW3', '2019', 33, 1),
	('lesautresmomentsinformels', 'Les autres moments informels', 'Toute la semaine', 'https://cloud.scic-tetris.org/s/hQm49icbbZdbVq1', '2019', 32, 1),
	('lessuitesducolloque', 'les suites du colloque', 'Après le colloque', 'https://cloud.scic-tetris.org/s/GB7S1F9AseG45kk', '2019', 34, 1),
	('makingoffducolloqueintroduction', 'Making off du colloque', 'Avant le colloque', 'https://cloud.scic-tetris.org/s/PIa2StPjHXmjmRB', '2019', 1, 1),
	('pleniere1democratieetsolidarite', 'Plénière 1 - Démocratie et solidarité', 'Samedi 13 Juillet', 'https://cloud.scic-tetris.org/s/ktIqwns5pFcVOcg', '2019', 5, 1),
	('pleniere2faireatterirlescommunsnumeriques', 'Plénière 2 - Faire attérir les communs numériques ', 'Dimanche 14 Juillet', 'https://cloud.scic-tetris.org/s/bBLB8bzIBHEmcM5', '2019', 9, 1),
	('pleniere3letempsdesmesorepubliquesintercooperatives', 'Plénière 3 - Le temps des méso-républiques inter-coopératives', 'Lundi 15 Juillet', 'https://cloud.scic-tetris.org/s/EiyPUqyW2569Nux', '2019', 10, 1),
	('pleniere4economiesymbiotiqueecologieetcommun', 'Plénière 4 - Economie symbiotique, écologie et commun', 'Mercredi 17 Juillet', 'https://cloud.scic-tetris.org/s/CXz9XxkWUPshyOa', '2019', 22, 1),
	('rapportsdetonnements', 'Rapports d\'étonnements', 'Vendredi 19 Juillet', 'https://cloud.scic-tetris.org/s/ZLMHtngrHCDk2s3', '2019', 31, 1),
	('soireeavecjacquesjouet', 'Soirée avec Jacques Jouet', 'Mardi 16 Juillet', 'https://cloud.scic-tetris.org/s/YFIXeFjK9iw4l6e', '2019', 19, 1),
	('soireepoemes', 'Soirée Poémes', 'Jeudi 18 Juillet', 'https://cloud.scic-tetris.org/s/FngdEOCfJNaCfev', '2019', 30, 1),
	('tr10educationpopulaireconstruireunmondecommun', 'TR 10 - Education populaire, construire un monde commun', 'Jeudi 18 Juillet', 'https://cloud.scic-tetris.org/s/yotIZdxgvwZq8qa', '2019', 27, 1),
	('tr1ressourcesdesterritoiresareveler', 'TR 1 - Ressources des territoires à révéler', 'Samedi 13 Juillet', 'https://cloud.scic-tetris.org/s/4ijULKqkvd1al8K', '2019', 3, 1),
	('tr2territoiressolidairesetemploi', 'TR 2 - Territoires solidaires et emploi', 'Samedi 13 Juillet', 'https://cloud.scic-tetris.org/s/E8bnyfbXQhw9HUE', '2019', 4, 1),
	('tr3energiedurableetterritoire', 'TR 3 - Energie durable et territoire', 'Mercredi 17 Juillet', 'https://cloud.scic-tetris.org/s/2Pi4qzxoB33WClF', '2019', 20, 1),
	('tr4systemesalimentairessolidairesterritorialises', 'TR 4 - Systèmes alimentaires solidaires territorialisés', 'Dimanche 14 Juillet', 'https://cloud.scic-tetris.org/s/JwE6n7Rgjdbj85E', '2019', 7, 1),
	('tr5cultureetcommundanslesterritoires', 'TR 5 - Culture et commun dans les territoires', 'Lundi 15 Juillet', 'https://cloud.scic-tetris.org/s/AoOyHBBdOtVxRpX', '2019', 11, 1),
	('tr6grandeentrepriseetterritoire', 'TR 6 - Grande entreprise et territoire', 'Lundi 15 Juillet', 'https://cloud.scic-tetris.org/s/7po4OW6Om0mXNt0', '2019', 12, 1),
	('tr7echellesterritorialesdelasanteencommun', 'TR 7 - Echelles territoriales de la santé en commun', 'Mardi 16 Juillet', 'https://cloud.scic-tetris.org/s/p7taRappvXgBNZn', '2019', 16, 1),
	('tr8habiterencommunlesterritoires', 'TR 8 - Habiter en commun les territoires', 'Mardi 16 Juillet', 'https://cloud.scic-tetris.org/s/aXh76XanJqlFQp4', '2019', 17, 1),
	('tr9frichesencommunetterritoires', 'TR 9 - Friches en commun et territoires', 'Jeudi 18 Juillet', 'https://cloud.scic-tetris.org/s/4xt1NEluftdbLRx', '2019', 26, 1);
/*!40000 ALTER TABLE `timeline` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
